version: 2

linters:
  default: standard
  enable:
    - unconvert
    - gosec
    - cyclop
    - revive
    - depguard

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*encoding/json.Decoder).Decode
        - (io.Closer).Close
        - (io/fs.File).Close
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (net/http.ResponseWriter).Write

    revive:
      max-open-files: 2048
      rules:
        - name: blank-imports
          severity: warning
          disabled: false
        - name: exported
          disabled: true
    gosec:
      excludes:
        - G115
        - G204
        - G104
        - G304
    cyclop:
      max-complexity: 30
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/aws/aws-sdk-go/"
              desc: use github.com/aws/aws-sdk-go-v2
run:
  tests: false
  timeout: 15m
  concurrency: 15
  relative-path-mode: gomod
  issues-exit-code: 2

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    paths:
      - ".*\\.gen\\.go$"
