services:
  dynamodb-local:
    image: amazon/dynamodb-local:3.1.0
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: dummy0creds
      AWS_SECRET_ACCESS_KEY: dummy0creds
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:5.1.3
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000

    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
