# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - id: tagpr
        uses: Songmu/tagpr@7191605433b03e11b313dbbc0efb80185170de4b # v1
      - name: Checkout released
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        if: ${{ steps.tagpr.outputs.tag != '' }}
        with:
          ref: ${{ steps.tagpr.outputs.tag }}
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v4
        if: ${{ steps.tagpr.outputs.tag != '' }}
        with:
            go-version: "1.21"
      - name: Run Go Releaser
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5
        if: ${{ steps.tagpr.outputs.tag != '' }}
        with:
          version: latest
          args: release
