name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.23"
          - "1.24"
          - "1.25"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@36eaff1005b37a22258716d4280f9e0377b834aa # v4.0.0
        with:
          port: 8000
          cors: "*"
      - name: Set up Go
        uses: actions/setup-go@0caeaed6fd66a828038c2da3c0f662a42862658f # v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: go test
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          DYNAMODB_LOCAL_ENDPOINT: http://localhost:8000
          AWS_DEFAULT_REGION: ap-northeast-1
        run: |
          go test -race -timeout 30s ./...
